### ISSUE TITLE
Windows XP SP3 Unsupported

### ISSUE THREAD

**Issue by LordGarfio** [Ahmadmansoor/x64dbgScript#1]
Hereby, would it be feasible to compile x64dbgScript with Windows XP support ?

Thank you in advaned.

**Comment by Ahmadmansoor** [comment]
Hi
I will try to check if possible.
Thanks for trying it. I need to install xp first :)
BR

**Comment by Ahmadmansoor** [comment]
for xp x32
![image](https://user-images.githubusercontent.com/7176580/156317202-c86ba324-6204-41ff-b2a0-b9f5a6c7af81.png)
![image](https://user-images.githubusercontent.com/7176580/156319728-609c7603-3a71-482e-996a-aa16865a8ceb.png)

[XPplugins32.zip](https://github.com/Ahmadmansoor/x64dbgScript/files/8167639/XPplugins32.zip)

**Comment by LordGarfio** [comment]
No more crash! works Nice. Up!

**Comment by Ahmadmansoor** [comment]
Don't forget to install dotnet and vc2015 runtime.
